In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot

In [14]:

#create path to csv file:
expenditure_path= path('Resources\Capital health expenditure_data.csv')

In [15]:
expenditure_df= pd.read_csv(expenditure_path)
expenditure_df.head()

,Series Name,Series Code,Country Name,Country Code,2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022]
0,Capital health expenditure (% of GDP),SH.XPD.KHEX.GD.ZS,Afghanistan,AFG,0.28592768,0.36722939,0.31406657,0.41934217,0.41568576,..
1,Capital health expenditure (% of GDP),SH.XPD.KHEX.GD.ZS,Africa Eastern and Southern,AFE,..,..,..,..,..,..
2,Capital health expenditure (% of GDP),SH.XPD.KHEX.GD.ZS,Africa Western and Central,AFW,..,..,..,..,..,..
3,Capital health expenditure (% of GDP),SH.XPD.KHEX.GD.ZS,Albania,ALB,0.14722906,0.16765136,..,..,..,..
4,Capital health expenditure (% of GDP),SH.XPD.KHEX.GD.ZS,Algeria,DZA,..,..,..,..,..,..

In [16]:
# Rename the columns
new_columns = {
    '2017 [YR2017]': '2017',
    '2018 [YR2018]': '2018',
    '2019 [YR2019]': '2019',
    '2020 [YR2020]': '2020',
    '2021 [YR2021]': '2021',
    '2022 [YR2022]': '2022'
}
expenditure_df = expenditure_df.rename(columns=new_columns)

In [17]:
# Rename the columns
new_columns = {
    '2017 [YR2017]': '2017',
    '2018 [YR2018]': '2018',
    '2019 [YR2019]': '2019',
    '2020 [YR2020]': '2020',
    '2021 [YR2021]': '2021',
    '2022 [YR2022]': '2022'
}
expenditure_df.rename(columns=new_columns)
# Check the modified DataFrame
expenditure_df.head()

,Series Name,Series Code,Country Name,Country Code,2017,2018,2019,2020,2021,2022
0,Capital health expenditure (% of GDP),SH.XPD.KHEX.GD.ZS,Afghanistan,AFG,0.28592768,0.36722939,0.31406657,0.41934217,0.41568576,..
1,Capital health expenditure (% of GDP),SH.XPD.KHEX.GD.ZS,Africa Eastern and Southern,AFE,..,..,..,..,..,..
2,Capital health expenditure (% of GDP),SH.XPD.KHEX.GD.ZS,Africa Western and Central,AFW,..,..,..,..,..,..
3,Capital health expenditure (% of GDP),SH.XPD.KHEX.GD.ZS,Albania,ALB,0.14722906,0.16765136,..,..,..,..
4,Capital health expenditure (% of GDP),SH.XPD.KHEX.GD.ZS,Algeria,DZA,..,..,..,..,..,..

In [18]:
# Select specific columns
columns_to_keep = ['Country Code', 'Country Name', '2017', '2018', '2019', '2020', '2021', '2022']
expenditure_df = expenditure_df[columns_to_keep]

# Set 'Country Name' as the index
expenditure_df = expenditure_df.set_index(keys=['Country Code','Country Name',])

# Stack the data
expenditure_df = expenditure_df.stack()

# Convert the stacked data to a DataFrame
expenditure_df = pd.DataFrame(expenditure_df)

# Reset the index to get a default numeric index
expenditure_df = expenditure_df.reset_index()

expenditure_df

     Country Code Country Name level_2           0
0             AFG  Afghanistan    2017  0.28592768
1             AFG  Afghanistan    2018  0.36722939
2             AFG  Afghanistan    2019  0.31406657
3             AFG  Afghanistan    2020  0.41934217
4             AFG  Afghanistan    2021  0.41568576
...           ...          ...     ...         ...
1591          ZWE     Zimbabwe    2018   0.1727162
1592          ZWE     Zimbabwe    2019  1.52644157
1593          ZWE     Zimbabwe    2020  0.11873686
1594          ZWE     Zimbabwe    2021          ..
1595          ZWE     Zimbabwe    2022          ..

[1596 rows x 4 columns]

In [19]:
# Rename the columns

expenditure_df.columns = ['Country Code', 'Country Name',  'Year', 'Capital Health Expenditure']

In [20]:
expenditure_df.head(10)

  Country Code                 Country Name  Year Capital Health Expenditure
0          AFG                  Afghanistan  2017                 0.28592768
1          AFG                  Afghanistan  2018                 0.36722939
2          AFG                  Afghanistan  2019                 0.31406657
3          AFG                  Afghanistan  2020                 0.41934217
4          AFG                  Afghanistan  2021                 0.41568576
5          AFG                  Afghanistan  2022                         ..
6          AFE  Africa Eastern and Southern  2017                         ..
7          AFE  Africa Eastern and Southern  2018                         ..
8          AFE  Africa Eastern and Southern  2019                         ..
9          AFE  Africa Eastern and Southern  2020                         ..

In [21]:
#Drop missing value
expenditure_df.replace('..', np.nan, inplace=True)
new_expenditure_df =expenditure_df.dropna()
new_expenditure_df.head(15)

   Country Code         Country Name  Year Capital Health Expenditure
0           AFG          Afghanistan  2017                 0.28592768
1           AFG          Afghanistan  2018                 0.36722939
2           AFG          Afghanistan  2019                 0.31406657
3           AFG          Afghanistan  2020                 0.41934217
4           AFG          Afghanistan  2021                 0.41568576
18          ALB              Albania  2017                 0.14722906
19          ALB              Albania  2018                 0.16765136
36          AND              Andorra  2017                 0.10919669
37          AND              Andorra  2018                 0.06971787
38          AND              Andorra  2019                 0.10289453
48          ATG  Antigua and Barbuda  2017                 0.00550222
49          ATG  Antigua and Barbuda  2018                 0.02265624
50          ATG  Antigua and Barbuda  2019                 0.02125437
51          ATG  Antigua and Barbuda  2020                 0.00856461
60          ARG            Argentina  2017                 0.00970424

In [22]:
# Write the new data to a CSV file namely: hygiene cleaned

newfile_path= path('Resources\Capital Health Expenditure cleaned.csv')
new_expenditure_df.to_csv(newfile_path, index=False)